language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - /home/travis/.cache/firebase/emulators
before_install:
  - curl -sL https://firebase.tools | bash
install:
  - npm install
script:
  - firebase use ${DEV_FIREBASE_PROJECT}
  - npm test
deploy:
  # Deploy to dev firebase project
  - provider: script
    script: bash ./deploy.sh DEV_FIREBASE_PROJECT
    skip-cleanup: true
    on:
      branch: master
  # Deploy to screenshots firebase project
  - provider: script
    script: bash ./deploy.sh SCREENSHOTS_FIREBASE_PROJECT
    skip-cleanup: true
    on:
      branch: master
  # Deploy to prod firebase project, only on git tags
  - provider: script
    script: bash ./deploy.sh PROD_FIREBASE_PROJECT
    skip-cleanup: true
    on:
      branch: master
      tags: true

