language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - /home/travis/.cache/firebase/emulators
before_install:
  - curl -sL https://firebase.tools | bash
install:
  - npm install
script:
  - firebase use $DEV_FIREBASE_PROJECT
  - npm test
deploy:
  # Deploy to dev firebase project
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $DEV_FIREBASE_PROJECT
    message: "Cloud function deployment to dev env."
    skip_cleanup: true
    on:
      branch: master
  # Deploy to dev firebase project
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $SCREENSHOTS_FIREBASE_PROJECT
    message: "Cloud function deployment to screenshots env."
    skip_cleanup: true
    on:
      branch: master
  # On tags, deploy to prod firebase project
  - provider: firebase
    token:
      secure: $FIREBASE_TOKEN
    project: $DEV_FIREBASE_PROJECT
    message: "Cloud function deployment to prod env."
    skip_cleanup: true
    on:
      branch: master
      tags: true
