language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - /home/travis/.cache/firebase/emulators
before_install:
  - curl -sL https://firebase.tools | bash
install:
  - npm install
script:
  - firebase use $DEV_FIREBASE_PROJECT
  - npm test
deploy:
  # Deploy to dev firebase project
  - provider: script
    script: bash ./deploy.sh DEV_FIREBASE_PROJECT
    cleanup: false
    on:
      branch: master
